UPDATE contest_type SET draw_one_title ='h.draw' WHERE draw_one_title = 'Draw';
UPDATE contest_type SET draw_one_title ='h.set-test-draw' WHERE draw_one_title = 'Set Test Draw';
UPDATE contest_type SET draw_one_title ='h.test-piece-draw' WHERE draw_one_title = 'Test Piece Draw';
UPDATE contest_type SET draw_two_title ='h.entertainment-draw' WHERE draw_two_title = 'Entertainment Draw';
UPDATE contest_type SET draw_two_title ='h.entertainment-draw' WHERE draw_two_title = 'Entertainments Draw';
UPDATE contest_type SET draw_two_title ='h.own-choice-draw' WHERE draw_two_title = 'Own Choice Draw';
UPDATE contest_type SET points_total_title ='h.points' WHERE points_total_title = 'Points';
UPDATE contest_type SET points_total_title ='h.total' WHERE points_total_title = 'Total';
UPDATE contest_type SET points_total_title ='h.total' WHERE points_total_title = 'Total Points';
UPDATE contest_type SET points_one_title ='h.adj-a' WHERE points_one_title = 'Adj A';
UPDATE contest_type SET points_one_title ='h.church' WHERE points_one_title = 'Church';
UPDATE contest_type SET points_one_title ='h.concert' WHERE points_one_title = 'Concert';
UPDATE contest_type SET points_one_title ='h.hymn' WHERE points_one_title = 'Hymn';
UPDATE contest_type SET points_one_title ='h.march' WHERE points_one_title = 'March';
UPDATE contest_type SET points_one_title ='h.music' WHERE points_one_title = 'Music';
UPDATE contest_type SET points_one_title ='h.own-choice' WHERE points_one_title = 'Own Choice';
UPDATE contest_type SET points_one_title ='h.quality-adj-1' WHERE points_one_title = 'Quality Adj 1';
UPDATE contest_type SET points_one_title ='h.set-test' WHERE points_one_title = 'Set Test';
UPDATE contest_type SET points_one_title ='h.adj-b' WHERE points_one_title = 'Adj B';
UPDATE contest_type SET points_two_title ='h.concert-item-1' WHERE points_two_title = 'Concert Item 1';
UPDATE contest_type SET points_two_title ='h.entertainment' WHERE points_two_title = 'Entertainment';
UPDATE contest_type SET points_two_title ='h.hymn' WHERE points_two_title = 'Hymn';
UPDATE contest_type SET points_two_title ='h.inspection' WHERE points_two_title = 'Inspection';
UPDATE contest_type SET points_two_title ='h.own-choice' WHERE points_two_title = 'Own Choice';
UPDATE contest_type SET points_two_title ='h.quality-adj-2' WHERE points_two_title = 'Quality Adj 2';
UPDATE contest_type SET points_two_title ='h.sacred' WHERE points_two_title = 'Sacred';
UPDATE contest_type SET points_two_title ='h.set-test' WHERE points_two_title = 'Set Test';
UPDATE contest_type SET points_two_title ='h.solo' WHERE points_two_title = 'Solo';
UPDATE contest_type SET points_two_title ='h.test-piece' WHERE points_two_title = 'Test Piece';
UPDATE contest_type SET points_three_title ='h.adj-c' WHERE points_three_title = 'Adj C';
UPDATE contest_type SET points_three_title ='h.concert-item-2' WHERE points_three_title = 'Concert Item 2';
UPDATE contest_type SET points_three_title ='h.deportment' WHERE points_three_title = 'Deportment';
UPDATE contest_type SET points_three_title ='h.entertainment' WHERE points_three_title = 'Entertainment';
UPDATE contest_type SET points_three_title ='h.music' WHERE points_three_title = 'Music';
UPDATE contest_type SET points_three_title ='h.own-choice' WHERE points_three_title = 'Own Choice';
UPDATE contest_type SET points_three_title ='h.programme' WHERE points_three_title = 'Programme';
UPDATE contest_type SET points_three_title ='h.test-piece' WHERE points_three_title = 'Test Piece';
UPDATE contest_type SET points_four_title ='h.entertainment' WHERE points_four_title = 'Entertainment';
UPDATE contest_type SET points_four_title ='h.stage-march' WHERE points_four_title = 'Stage March';
UPDATE contest_type SET points_penalty_title ='h.penalty' WHERE points_penalty_title = 'Penalty';
