debug: true
logging:
  level:
    org:
      springframework:
        security: INFO
      apache:
        http: INFO
spring:
  profiles:
    active: prod
  datasource:
    url: ${BBR_DATABASE_URL}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${BBR_DATABASE_USERNAME}
    password: ${BBR_DATABASE_PASSWORD}
  jpa:
    open-in-view: false
    # show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
  mail:
    password: ${BBR_SMTP_SERVER_PASSWORD}
    username: ${BBR_SMTP_SERVER_USERNAME}
    host: ${BBR_SMTP_SERVER_HOST}
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
    packagesToScan: uk.co.bbr.api
azure:
  cosmosdb:
    uri: ${BBR_COSMOS_DB_URI}
    access-key: ${BBR_COSMOS_DB_ACCESS_KEY}
    database: ${BBR_COSMOS_DB_NAME}
