spring:
  datasource:
    url: jdbc:sqlserver://timpi;database=bbr;trustServerCertificate=true
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: admin9552Password
  jpa:
    open-in-view: false
    # show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
  mail:
    password: ${SMTP_SERVER_PASSWORD}
    username: ${SMTP_SERVER_USERNAME}
    host: ${SMTP_SERVER_HOST}
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true