SELECT 'INSERT INTO contest_type(old_id, updated, created, updated_by_id, owner_id, name, slug, translation_key, draw_one_title, draw_two_title, draw_three_title, points_total_title, points_one_title, points_two_title, points_three_title, points_four_title, points_penalty_title, has_test_piece, has_own_choice, has_entertainments, statistics_show, statistics_limit) VALUES ('
    || id || ', '
|| '''' || last_modified || ''', '
|| '''' || created || ''', '
'1, '
'1, '
|| '''' || name || ''', '
|| '''' || LOWER(REPLACE(name,' ', '-')) || ''', '
|| 'contest-types.' || LOWER(REPLACE(name,' ', '-')) || ''','
|| '''' || first_draw || ''', '
|| '''' || second_draw || ''', '
|| 'null, '
|| '''' || total_points || ''', '
|| '''' || points_one || ''', '
|| '''' || points_two || ''', '
|| '''' || points_three || ''', '
|| '''' || points_four || ''', '
|| '''' || penalty_points || ''', '
|| '''' || test_piece || ''', '
|| '''' || own_choice || ''', '
|| '''' || entertainments || ''', '
|| '''' || statistics || ''', '
|| '''' || statistics_limit || ''', '
|| ');'
FROM contests_contesttype ORDER BY id;