name: destroy

on:
  pull_request_target:
    types: [closed]

jobs:
  authorize:
    environment:
      ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: true

  destroy:
    needs: [authorize]
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
      -
        name: Terraform fmt
        run: cd terraform && terraform fmt -check
      -
        name: Terraform Init
        env:
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
        run: cd terraform && terraform init -upgrade && terraform workspace select pr-${{ github.event.number }} || terraform workspace new pr-${{ github.event.number }}
      -
        name: Terraform Validate
        run: terraform validate
      -
        name: Terraform Destroy
        env:
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_smtp_hostname: ${{ secrets.TF_VAR_smtp_hostname }}
          TF_VAR_smtp_username: ${{ secrets.TF_VAR_smtp_username }}
          TF_VAR_smtp_password: ${{ secrets.TF_VAR_smtp_password }}
          TF_VAR_docker_image_tag: pr-${{ github.event.number }}-${{ github.run_number }}
          TF_VAR_cloudflare_zone_id: ${{ secrets.TF_VAR_cloudflare_zone_id }}
          TF_VAR_stripe_public_buy_button: ${{ secrets.TF_VAR_stripe_TEST_public_buy_button }}
          TF_VAR_stripe_public_publishable_key: ${{ secrets.TF_VAR_stripe_TEST_public_publishable_key }}
          TF_VAR_stripe_private_api_key: ${{ secrets.TF_VAR_stripe_TEST_private_api_key }}      
        run: |
          cd terraform && terraform destroy -auto-approve
          terraform workspace select default
          terraform workspace delete pr-${{ github.event.number }}
