name: terraform-plan

on:
  pull_request:
    paths:
      - 'terraform/**'
  release:
    types: [created]
 
jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2
      -
        name: Terraform fmt
        run: cd terraform && terraform fmt -check
      -
        name: Terraform Init
        env:
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
        run: cd terraform && terraform init
      -
        name: Terraform Validate
        run: terraform validate
      -
        name: Terraform Plan
        env:
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
          TF_VAR_database_admin_username: ${{ secrets.TF_VAR_database_admin_username }}
          TF_VAR_database_admin_password: ${{ secrets.TF_VAR_database_admin_password }}
        run: cd terraform && terraform plan
