name: terraform-plan

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
 
jobs:
  authorize:
    environment:
      ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: true

  terraform-plan:
    needs: authorize
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      -
        name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2
      -
        name: Terraform fmt
        run: cd terraform && terraform fmt -check
      -
        name: Terraform Init
        env:
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
        run: cd terraform && terraform init && terraform workspace select prod
      -
        name: Terraform Validate
        run: terraform validate
      -
        name: Terraform Plan
        env:
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_smtp_hostname: ${{ secrets.TF_VAR_smtp_hostname }}
          TF_VAR_smtp_username: ${{ secrets.TF_VAR_smtp_username }}
          TF_VAR_smtp_password: ${{ secrets.TF_VAR_smtp_password }}
          TF_VAR_cloudflare_zone_id: ${{ secrets.TF_VAR_cloudflare_zone_id }}
        run: cd terraform && terraform plan -lock=false
