name: test

on:
  push:
    paths:
      - 'site/**'
  pull_request:
    paths:
      - 'site/**'

jobs:
  test:
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      -
        name: Set up Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      -
        name: Test
        run: cd site && ./mvnw --batch-mode test
        timeout-minutes: 15
